version: '3.9'

services:
  aesm:
    image: initc3/linux-sgx:2.13-ubuntu20.04
    devices:
      - /dev/isgx
    volumes:
      - aesmd-socket:/var/run/aesmd
      #- ./aesmd.conf:/etc/aesmd.conf
    user: aesmd
    #stdin_open: true
    #tty: true
    working_dir: /opt/intel/sgx-aesm-service/aesm
    environment:
      LD_LIBRARY_PATH: /opt/intel/sgx-aesm-service/aesm
    command: ./aesm_service --no-daemon

  dev:
    image: sgx_voting_dev
    build:
      context: .
      dockerfile: dev.Dockerfile
      #args:
      #  SGX_MODE: hw
      #  SGX_DEBUG: 0
    depends_on:
      - aesm
    devices:
      - /dev/isgx
    environment:
      SGX_SPID: ${SGX_SPID}
      IAS_PRIMARY_KEY: ${IAS_PRIMARY_KEY}
      PYTHONBREAKPOINT: ipdb.set_trace
      SGX_DEBUG: 1
    volumes:
      - aesmd-socket:/var/run/aesmd
      - /var/run/docker.sock:/var/run/docker.sock
      - ./makefile:/usr/src/sgxvoting/makefile
      - ./common:/usr/src/sgxvoting/common
      - ./app:/usr/src/sgxvoting/app
      - ./enclave:/usr/src/sgxvoting/enclave
      - ./interface:/usr/src/sgxvoting/interface
      - ./trustedLib:/usr/src/sgxvoting/trustedLib
      # - ./run_demo_sgxra.sh:/usr/src/sgxvoting/run_demo_sgxra.sh
      - ./test.sh:/usr/src/sgxvoting/test.sh
      - ./run_election.sh:/usr/src/sgxvoting/run_election.sh
      - ./demo_sgx:/usr/src/sgxvoting/demo_sgx
    command: bash

volumes:
  aesmd-socket:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "rw"
